# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

In [ ]:
np.random.seed(0)
matrix = np.random.rand (4, 7)*20
print(f'Матрица:\n{matrix}')
normalized_matrix = np.around(matrix-np.min(matrix))/(np.max(matrix)-np.min(matrix))
print('Нормализованная матрица:\n',normalized_matrix)

Матрица:
[[10.97627008 14.30378733 12.05526752 10.89766366  8.47309599 12.91788226
   8.75174423]
 [17.83546002 19.27325521  7.66883038 15.83450076 10.5778984  11.36089122
  18.51193277]
 [ 1.42072116  1.74258599  0.40436795 16.65239691 15.56313502 17.40024296
  19.57236684]
 [15.98317128  9.22958725 15.61058353  2.36548852 12.79842043  2.86706575
  18.89337834]]
Нормализованная матрица:
 [[0.57387315 0.73038402 0.62604344 0.52170287 0.41736229 0.67821373
  0.41736229]
 [0.88689488 0.99123545 0.36519201 0.7825543  0.52170287 0.57387315
  0.93906516]
 [0.05217029 0.05217029 0.         0.83472459 0.7825543  0.88689488
  0.99123545]
 [0.83472459 0.46953258 0.7825543  0.10434057 0.62604344 0.10434057
  0.93906516]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
matrix = np.random.randint(0, 10, (8, 10))
print('Матрица:\n', matrix)
matrix_2 = matrix[np.argmin(np.sum(matrix, axis=1))]
print('Строка матрицы с наименьшей суммой:', matrix_2)
matrix_2 = sum(matrix[0])
for i in range(len(matrix)): 
  if sum(matrix[i]) < matrix_2:
    matrix_2 = sum(matrix[i])
    index = i
print(f'Индекс строки: {index}')
print(f'Сумма элементор строки равна: {matrix_2}')

Матрица:
 [[1 4 7 8 7 7 9 9 0 6]
 [3 7 2 6 3 5 8 9 5 0]
 [6 9 1 4 7 5 2 6 4 7]
 [3 6 7 0 6 4 2 3 2 0]
 [9 5 8 1 0 9 5 9 2 1]
 [3 0 6 0 7 9 3 8 4 4]
 [5 1 6 8 6 1 4 4 9 8]
 [6 2 3 8 0 5 8 7 5 6]]
Строка матрицы с наименьшей суммой: [3 6 7 0 6 4 2 3 2 0]
Индекс строки: 3
Сумма элементор строки равна: 33


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
dot_1 = np.array((0,0,0))
dot_2 = np.array((3,3,3))
evklidovo_distance = np.sqrt(sum(pow(a-b, 2) for a, b in zip(dot_1, dot_2)))
print(evklidovo_distance)

5.196152422706632


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np
ingredients= np.loadtxt('/content/minutes_n_ingredients.csv',delimiter = ',', dtype = 'int32', skiprows = 1) # skiprows аргумент, который определяет, какие строки в файле csv используются
print(ingredients[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
import pandas as pd
recipe = pd.read_csv("/content/minutes_n_ingredients.csv")
recipe.describe()

id       minutes  n_ingredients
count  100000.000000  1.000000e+05  100000.000000
mean   222064.323910  2.160100e+04       9.055280
std    141119.154855  6.790939e+06       3.737278
min        38.000000  0.000000e+00       1.000000
25%    100017.750000  2.000000e+01       6.000000
50%    207193.500000  4.000000e+01       9.000000
75%    333810.500000  6.500000e+01      11.000000
max    537671.000000  2.147484e+09      39.000000

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
recipe_time = ingredients[:,1]
print('Значение квантеля:', np.quantile(recipe_time , 0.75))
print('\n',ingredients[ingredients[:,1] <= np.quantile(recipe_time , 0.75)])

Значение квантеля: 65.0

 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте для скольких рецептов указана продолжительность равная 0. Замените значение этих столбцов на 1.

In [ ]:
print('Продолжительность равная 0:',np.sum(ingredients==0))
ingredients[ingredients==0]=1

Продолжительность равная 0: 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
len(np.unique(ingredients[:,0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
unique = np.unique(ingredients[:,2])
num = len(np.unique(ingredients[:,2]))
print('Уникальные значения:', *unique, sep=',')
print('Количество уникальных значений:', num)

Уникальные значения:,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,37,39
Количество уникальных значений: 37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
array = ingredients[ingredients[:,2] <= 5]
new_array = ingredients[ingredients[:,2] <= 5]
print(new_array,'\n\n',ingredients)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]] 

 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
medium_ingredients = ingredients[:,2]/ingredients[:,1]
print('Максимальное значение величины:', max(medium_ingredients))

Максимальное значение величины: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
top_ingredients = ingredients[ingredients[:,1].argsort()[::-1]]
np.average(top_ingredients[:100,2])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
recipe = np.random.randint(ingredients.shape[0], size = 10)
print(ingredients[recipe])

[[228072     15      6]
 [499924     10      4]
 [149519     40     12]
 [261013     45     15]
 [216721    100      7]
 [186139      7      6]
 [412384     40     10]
 [165151     40     10]
 [397867     80      4]
 [190919     60      8]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
print('Процент рецептов, кол-во ингредиентов в которых меньше среднего:',((len(ingredients[ingredients[:,2]<(np.mean(ingredients[:,2]))]))/len(ingredients))*100)

Процент рецептов, кол-во ингредиентов в которых меньше среднего: 58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
recipe_new = (ingredients[:,1] <= 20) & (ingredients[:,2] <= 5), np.append(ingredients, np.full((len(ingredients),1),1).reshape(len(ingredients),1), axis=1)
print(recipe_new)

(array([False, False, False, ..., False,  True, False]), array([[127244,     60,     16,      1],
       [ 23891,     25,      7,      1],
       [ 94746,     10,      6,      1],
       ...,
       [498432,     65,     15,      1],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      1]]))


In [ ]:
simple_numbers=np.full((100000,1), 0)
for i in range(len(array)):
  if ingredients[i][1]<=20 and ingredients[i][2]<=5:
    simple_numbers[i][0]=1

simple_array=np.append(ingredients, simple_numbers, axis=1)
simple_array

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      0],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [ ]:
print((100*len(simple_array[simple_array[:,3] == 1]))/len(ingredients))

NameError: ignored

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
short_recipe = ingredients[ingredients[:,1]<10]
standart_recipe = ingredients[(ingredients[:,1]>=10) & (ingredients[:,1]<20)]
long_recipe = ingredients[ingredients[:,1]>=20]
max = min(len(short_recipe), len(standart_recipe), len(long_recipe))
np.array([short_recipe[:max-1], standart_recipe[:max-1], long_recipe[:max-1]])

array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [  2778,      1,     11],
        [420725,      5,      3],
        [  4747,      1,      9]],

       [[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [107094,     10,      4],
        [  9831,     15,      7],
        [335859,     12,     14]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [ 92137,     80,      9],
        [168901,     25,      7],
        [392339,     35,     13]]], dtype=int32)